<script src="{{ asset('public/assets/admin/vendors/js/vendors.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/vendors/js/charts/raphael-min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/vendors/js/charts/morris.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/vendors/js/extensions/unslider-min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/vendors/js/timeline/horizontal-timeline.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/core/app-menu.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/core/app.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/scripts/customizer.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/scripts/pages/dashboard-ecommerce.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/select2.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/custom.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/ckeditor/ckeditor.js') }}" type="text/javascript"></script> 
<script src="{{ asset('public/assets/admin/js/jquery.nestable.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/star_ratings.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/image_upload.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/jquery-ui.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/multi_images_upload.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/single_image_upload.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/admin/js/bootstrap-datetimepicker.js') }}" type="text/javascript"></script>